[build]
builder = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api"
restartPolicyType = "on_failure"
numReplicas = 1

[env]
PORT = "3000"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"