[build]
builder = "NIXPACKS"

[phases.setup]
# instala Node e Python juntos
nixPkgs = ["nodejs", "python3", "gcc"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt || echo 'Sem dependÃªncias Python'"
]

[start]
cmd = "npm start"
